feat: add mobile header
jordyfontoura/coopera-frontend pull request #6
Opened 2024-03-27 17:25 UTC by carolinenomura

2024-03-27 22:10 UTC, jordyfontoura requested changes

2024-03-27 22:10 UTC, jordyfontoura commented on public/menu.svg
Que tal criar uma pasta `public/icons` e deixar os icones nela?

2024-03-27 22:10 UTC, jordyfontoura commented on components/header.component.tsx
> +      <div className={styles.nav}>
Será que não faz mais sentido essa `div` ser um `nav`?

2024-03-27 22:10 UTC, jordyfontoura commented on styles/header.module.scss
> +    .nav {
Se for mudar aquela `div` para `nav`, lembra de mudar esse cara aqui para `nav` em vez de `.nav`

2024-03-27 22:10 UTC, jordyfontoura commented on styles/header.module.scss
> +      .nav {
Se for mudar aquela div para nav, lembra de mudar esse cara aqui para nav em vez de .nav

2024-03-27 22:12 UTC, jordyfontoura commented on components/header.component.tsx
> +      <div className={styles.nav}>
Aproveitando, acho que fazendo essa mudança, esse attributo `className` nem vai ser necessário

2024-03-27 22:13 UTC, jordyfontoura commented on styles/header.module.scss
> +        list-style-type: none;
Pode colocar esse cara em globals, ou então num arquivo `normalize.scss` e impotar ele em `globals.scss`

2024-03-27 23:40 UTC, jordyfontoura commented on styles/header.module.scss
Uma dúvida, vc prefere deixar os arquivos scss que estilizam os componentes na pasta styles ou junto com o componente?
Ex:
```
components
    header.component.tsx
    header.module.scss
```
Ou da forma que está?

2024-03-28 21:36 UTC, carolinenomura commented on styles/header.module.scss
> +        list-style-type: none;
Movi ele pra globals

2024-03-28 22:13 UTC, carolinenomura commented on styles/header.module.scss
Pensando pelo lado da modularização, junto com o componente. E nesse caso, cria uma subpasta pra cada componente contendo o tsx e o scss ou deixa tudo dentro de components?

2024-03-29 02:35 UTC, jordyfontoura commented on styles/header.module.scss
Como discutimos no chat, vamos seguir com essa arquitetura aqui:
```
components // Componentes de aplicação
  layout // Componentes de layout
    header // Componente de cabeçalho
      header.component.tsx // Para componentes
      header.module.scss // Para estilos
      header.component.spec.tsx // Para testes
      header.service.ts // Para serviços
    footer
      footer.component.tsx // Para componentes
      footer.module.scss // Para estilos
      footer.component.spec.tsx // Para testes
      footer.service.ts // Para serviços
```

2024-03-29 15:32 UTC, jordyfontoura commented on components/layout/header/header.module.scss
> +    margin: 10px 80px;
Aqui nessa linha, vamos preferir por usar padding
![image](https://github.com/jordyfontoura/coopera-frontend/assets/52868800/5c259362-335c-422c-a1b9-29286999c1a6)
Solução:
![image](https://github.com/jordyfontoura/coopera-frontend/assets/52868800/218af688-b4b0-4479-99a5-cfe141139543)

2024-03-29 19:36 UTC, jordyfontoura approved these changes

2024-03-29 19:36 UTC, merged